apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-pvc
  namespace: default
  labels:
    app: unifi-controller
  annotations:
    argocd.argoproj.io/tracking-id: unifi-controller:/PersistentVolumeClaim:default/unifi-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath-immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-mongo-pvc
  namespace: default
  labels:
    app: unifi-controller
  annotations:
    argocd.argoproj.io/tracking-id: unifi-controller:/PersistentVolumeClaim:default/unifi-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath-immediate
