apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config-pvc
  namespace: default
  labels:
    app: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath-immediate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-mongo-pvc
  namespace: default
  labels:
    app: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: microk8s-hostpath-immediate
